# Generated by Django 4.2.5 on 2023-09-21 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('botanical_name', models.CharField(max_length=100, null=True)),
                ('details', models.TextField(null=True)),
            ],
        ),
    ]
