# Generated by Django 4.2.5 on 2023-10-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='slug',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='slug',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
