name: Build

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      # https://github.com/orgs/community/discussions/26686#discussioncomment-3396593
      - name: Get tag name
        run: |
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"

      - name: Docker Log In
        run: |
          docker logout
          echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: make docker-build VERSION=${{ github.ref_name }}

      - name: Push Docker image
        run: make docker-push VERSION=${{ github.ref_name }}

      - name: Docker Log Out
        run: docker logout
